source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OpinionzAlertView_Example', :exclusive => true do
  pod "OpinionzAlertView",
end

target 'OpinionzAlertView_Tests', :exclusive => true do
  pod "OpinionzAlertView",

  
end
